name: tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install .
    - name: Test with pytest
      env:
        TFL_API_TOKEN: ${{ secrets.TFL_API_TOKEN }}
      run: |
        pip install pytest
        pip install pytest-cov
        pytest test_pyfl/test.py
